Operaciones de matrices
itaquito/python pull request #13
Opened 2023-09-08 22:53 UTC by SamMtz13

2023-09-08 23:40 UTC, itaquito requested changes

2023-09-08 23:40 UTC, itaquito commented on docs/numpy/matrices.md
> +### **Hay mas tipos de matrices, pero esto no es curso de Algebra Lineal. 😅**
Quita el título, está bien si sólo se queda el texto en negritas y ya

2023-09-08 23:40 UTC, itaquito commented on docs/numpy/operacionesmatrices.md
> +
Estaría bien añadr una pequeña descripción explicando que Numpy tiene varios métodos para realizar operaciones de matrices

2023-09-08 23:40 UTC, itaquito commented on docs/numpy/matrices.md
> +```python title="Creación de una matriz Traspuesta en python"
transpuesta*

2023-09-08 23:40 UTC, itaquito commented on docs/numpy/matrices.md
>  La Matriz Traspuesta de cualquier matriz es aquella que se obtiene al cambiar las filas por las columnas de una matriz. Por ejemplo:
transpuesta*

2023-09-08 23:40 UTC, itaquito commented on docs/numpy/operacionesmatrices.md
> +#### ➗ División de un escalar por una matriz
Este título debería de ser sólo con tres ###

2023-09-08 23:49 UTC, SamMtz13 commented on docs/numpy/matrices.md
> +```python title="Creación de una matriz Traspuesta en python"
En internet me puso traspuesta 0_o, ahorita lo corrijo

2023-09-08 23:52 UTC, SamMtz13 commented on docs/numpy/operacionesmatrices.md
> +#### ➗ División de un escalar por una matriz
Ah es que siento que es un subtema ya que no es muy comun de hacerlo

2023-09-09 00:06 UTC, itaquito commented on docs/numpy/operacionesmatrices.md
> +#### ➗ División de un escalar por una matriz
De todas formas, si los dejas con `####` estás diciendo que `División de un escalar por una matriz` es un subtítulo de `Multiplicación de una matriz por un escalar`.

2023-09-09 05:03 UTC, itaquito requested changes

2023-09-09 05:03 UTC, itaquito commented on docs/numpy/matrices.md
> +El método where() nos permite encontrar los indices de los elementos de una matriz que cumplan una condición. Por ejemplo:
índices*

2023-09-09 05:03 UTC, itaquito commented on docs/numpy/matrices.md
> +np.where(matriz>5)
Añadir la alternativa al método `where` que es poner la condición dentro de `[]`

2023-09-09 05:03 UTC, itaquito commented on docs/numpy/operaciones-matrices.md
> +En numpy podemos realizar operaciones con matrices, estas operaciones pueden ser entre matrices y escalares o entre matrices y matrices.
Numpy*

2023-09-09 05:03 UTC, itaquito commented on docs/numpy/matrices.md
> +**Hay mas tipos de matrices, pero esto no es curso de Algebra Lineal. 😅**
Álgebra*

2023-09-09 05:03 UTC, itaquito commented on docs/numpy/matrices.md
> +La Matriz Transpuesta de cualquier matriz es aquella que se obtiene al cambiar las filas por las columnas de una matriz. Por ejemplo:
matriz transpuesta no lleva mayúscula

2023-09-09 05:03 UTC, itaquito commented on docs/numpy/matrices.md
> +```python title="Creación de una matriz Transpuesta en python"
transpuesta no lleva mayúscula

2023-09-09 05:17 UTC, itaquito requested changes

2023-09-09 05:17 UTC, itaquito commented on docs/numpy/matrices.md
>  ### 6️⃣ Matriz Unidad(Identidad)
falta un espacio antes del paréntesis

2023-09-09 05:17 UTC, itaquito commented on docs/numpy/matrices.md
>  La Matriz Identidad es una matriz cuadrada que tiene todos sus elementos de la diagonal principal iguales a 1 y los demás elementos iguales a cero. Por ejemplo:
identidad no lleva mayúscula

2023-09-09 05:17 UTC, itaquito commented on docs/numpy/matrices.md
> +```python title="Creación de una matriz identidad(3x3) en python"
falta un espacio antes del paréntesis

2023-09-09 05:17 UTC, itaquito commented on docs/numpy/matrices.md
>  Las Matrices Triangulares son aquellas que tienen todos sus elementos por encima o por debajo de la diagonal principal iguales a cero. Existen dos tipos de Matrices Triangulares: Matriz Triangular Su
matrices triangulares no lleva mayúscula

2023-09-09 05:17 UTC, itaquito commented on docs/numpy/matrices.md
>  ![Matriz triangular](/img//numpy/matrices/triangular.jpg)
Hay una doble diagonal aquí

2023-09-09 19:22 UTC, SamMtz13 commented on docs/numpy/matrices.md
> +Este metodo nos permite encontrar el las dimensiones(Número de columnas y de filas) de una matriz.
Lo corregi  por atributo

2023-09-09 19:27 UTC, itaquito approved these changes

2023-09-09 19:27 UTC, merged